[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/equipe/equipe-1/"

[[redirects]]
from = "/equipe/kyara-amourdom/alternatives/"
to = "/equipe/kyara-amourdom/usages/"

[[redirects]]
from = "/alternatives/2025-04-09-traduire-des-mots-ou-des-textes/"
to = "/usages/2025-04-09-traduire-des-mots-ou-des-textes/"

[[redirects]]
from = "/equipe/margaux-astabie/alternatives/"
to = "/equipe/margaux-astabie/usages/"

[[redirects]]
from = "/projets/"
to = "/alternatives/"

[[redirects]]
from = "/alternatives/2025-04-09-obtenir-des-sources-et-des-informations/"
to = "/usages/2025-04-09-obtenir-des-sources-et-des-informations/"

[[redirects]]
from = "/alternatives/usages/"
to = "/alternatives/besoins/"

[[redirects]]
from = "/alternatives/2025-04-09-corriger-des-mots-ou-des-textes/"
to = "/usages/2025-04-09-corriger-des-mots-ou-des-textes/"

[[redirects]]
from = "/alternatives/2025-pixabay-2/"
to = "/alternatives/2025-pixabay/"

[[redirects]]
from = "/alternatives/usages/correction/"
to = "/alternatives/besoins/correction/"

[[redirects]]
from = "/actualites/"
to = "/usages/"

[[redirects]]
from = "/equipe/driss-chiari-noblet/alternatives/"
to = "/equipe/driss-chiari-noblet/usages/"

[[redirects]]
from = "/equipe/phuc-nguyen/alternatives/"
to = "/equipe/phuc-nguyen/usages/"

[[redirects]]
from = "/alternatives/usages/inspiration/"
to = "/alternatives/besoins/inspiration/"

[[redirects]]
from = "/alternatives/besoins/assistant/"
to = "/alternatives/besoins/assistant-juridique/"

[[redirects]]
from = "/alternatives/usages/corriger-des-mots-ou-des-textes/"
to = "/alternatives/besoins/correction/"

